config/routes.rb
Rails.application.routes.draw do

  resources :topics, only: [:index, :show]

  resources :comments
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do     #Toutes les ressources sauf le show qu'on fait nous meme
    put :sort, on: :collection
  end


  get 'mon-portfolio/:id', to: 'portfolios#show', as: 'portfolio_show' #cet alias portfolio_show est appele depuis la vue dans index de portfolio

  # get 'pages/home'  #this was there but we commented it
  # get 'pages/about'
  get 'about-thomas', to: 'pages#about'

  # get 'pages/contact'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  #Pour la partie commentaires des blogs
  mount ActionCable.server => '/cable'

  #ca va dire que la default page c'est ca
  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1 }
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body, :topic_id #Pour obliger de remplir ces valeurs

  belongs_to :topic

  has_many :comments, dependent: :destroy

  def self.first_two_blogs
    limit(2)
  end

  def self.recent
    order("created_at DESC")
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  layout "blog"  #same as layout("blog") TAKE THE CSS FILE
  access all: [:show, :index], user:{except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all

  # GET /blogs
  # GET /blogs.json
  def index

    @blogs = logged_in?(:site_admin) ? Blog.recent.page(params[:page]).per(5) : Blog.published.recent.page(params[:page]).per(5)
    #
    #@blogs = Blog.first_two_blogs
    @page_title = "Portfolio blog page"
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    if logged_in?(:site_admin) || @blog.published?
      @blog = Blog.includes(:comments).friendly.find(params[:id])
      @comment = Comment.new

      @page_title = @blog.title
      @seo_keywords = @blog.body
      else
        redirect_to blogs_path, notice: "You are not authorized to access this page"
    end
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    #pas dans le tuto mais il me faut un topic pour la BDD donc j'en ai mis un
    #@blog.topic = Topic.last

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status

    if @blog.draft?
      @blog.published!
    elsif @blog.published?
       @blog.draft!
         end

    redirect_to blogs_url, notice: 'Post status has been updated'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :topic_id, :status)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def gravatar_helper(user)
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 60
  end

  def blog_status_color(blog)
    'color: red;' if blog.draft?
  end


  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)

    options = {
        fenced_code_blocks: true,
        no_intra_emphasis: true,
        autolink: true,
        lax_html_blocks: true,
    }

    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end


end

app/views/blogs/_admin_actions.html.erb
<% if logged_in?(:site_admin) %>

  <nav class="breadcrumb blogcrumb">
    <%= link_to fa_icon('file-text'), toggle_status_blog_path(blog), style: blog_status_color(blog) %>
    <%= link_to fa_icon('pencil-square-o'), edit_blog_path(blog) %>
    <%= link_to fa_icon('trash'), blog, method: :delete, data: { confirm: 'Are you sure?' } %>
  </nav>
<% end %>

app/views/blogs/_blog.html.erb
<!--
<tr>
  <td><%= blog.title.upcase %></td>
  <td>Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</td>
  <td><%= blog.body %></td>

</tr>
-->

<div class="col-md-6">
  <%= render partial: 'blogs/admin_actions', locals: { blog: blog } %>
  <div class="card flex-md-row mb-4 shadow-sm h-md-250">
    <div class="card-body d-flex flex-column align-items-start">
      <strong class="d-inline-block mb-2 text-primary"><%= link_to blog.status, toggle_status_blog_path(blog) %></strong>
      <h3 class="mb-0">
        <a class="text-dark" href="#"><%= blog.title.upcase %></a>
      </h3>
      <div class="mb-1 text-muted">Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</div>
      <p class="card-text mb-auto"><%= blog.body %></p>
      <%= link_to 'Continue reading', blog %>
    </div>
  </div>
</div>

app/views/blogs/_form.html.erb
<%= form_for(blog) do |form| %>
  <% if blog.errors.any? %>

    <%= blog.errors.full_messages.each do | err | %>
      <%= alert_generator err %>
    <% end %>

    <div id="error_explanation">
      <p>La version error sans cocoon: </p>
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :title, class: 'form-control', placeholder: 'Title' %>
  </div>

  <div class="form-group">
    <%= form.label :topic_id %>
    <%= form.collection_select(:topic_id, Topic.all, :id, :title,
      {
          selected: blog.topic.present? ? blog.topic.id : nil,
          include_blank: true,
      },
      class: 'form_control'
      ) %>
  </div>

  <div class="form-group">
    <%= form.radio_button :status, 'draft' %>
    <%= form.label :status, 'Draft' %>

    <%= form.radio_button :status, 'published' %>
    <%= form.label :status, 'Published' %>
  </div>

  <div class="form-group">
    <%= form.text_area :body, class: 'form-control', rows: 15, placeholder: 'Body' %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="col-sm-8 blog-main"

  <h1>Editing Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Show', @blog %> |
  <%= link_to 'Back', blogs_path %>

</div>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs page</h1>


<%= link_to 'New Blog', new_blog_path if logged_in?(:site_admin) %>
<br/><br/>

<div class="row mb-2">
  <%= render @blogs %> <%# ici il cherche un partial appelé _blog au singulier, et il fait un foreach avec !!! %>
</div>

<div class="apple_pagination">
  <%= paginate @blogs %>
</div>

app/views/blogs/new.html.erb
<div class="col-sm-8 blog-main">

  <h1>New Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Back', blogs_path %>

</div>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  Topic: <%= @blog.topic.title %>
</p>

<nav class="breadcrumb">
  <%= link_to "Home", root_path, class: 'breadcrumb-item' %>
  <%= link_to @blog.topic.title, topic_path(@blog.topic), class: 'breadcrumb-item' %>

  <span class="breadcrumb-item active"><%= @blog.title %></span>

  <span class="pull-right">
      <%= link_to fa_icon('pencil-square-o'), edit_blog_path(@blog) if logged_in?(:site_admin) %>
    <%= link_to fa_icon('trash'), @blog, method: :delete, data: { confirm: 'Are you sure you want to delete this post' } if logged_in?(:site_admin) %>
    </span>
</nav>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
  <%= markdown @blog.body %>
</p>

<%= render 'comments/comment_form' %>

<div id="comments" data-blog-id="<%= @blog.id %>">
  <%= render @blog.comments %>
</div>

<br/><br/>

<%= link_to 'Edit', edit_blog_path(@blog) if logged_in?(:site_admin) %> |
<%= link_to 'Back', blogs_path %>