config/routes.rb
Rails.application.routes.draw do

  resources :topics, only: [:index, :show]

  resources :comments
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do     #Toutes les ressources sauf le show qu'on fait nous meme
    put :sort, on: :collection
  end


  get 'mon-portfolio/:id', to: 'portfolios#show', as: 'portfolio_show' #cet alias portfolio_show est appele depuis la vue dans index de portfolio

  # get 'pages/home'  #this was there but we commented it
  # get 'pages/about'
  get 'about-thomas', to: 'pages#about'

  # get 'pages/contact'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  #Pour la partie commentaires des blogs
  mount ActionCable.server => '/cable'

  #ca va dire que la default page c'est ca
  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  #has_many :technologies
  # accepts_nested_attributes_for :technologies, reject_if: lambda { |x| x['name'].blank? }
  #
  include Placeholder
  validates_presence_of :title, :body, :main_image, :thumb_image

  #Bug qund on met ca pour l image upload
  #mount_uploader :thumb_image, PortfolioUploader
  #mount_uploader :main_image, PortfolioUploader

  def self.wrc
    where(title: 'Dernier Portfolio WRC')
  end

  def self.by_position
    order("position ASC")
  end

  scope :specific_portfolio_items, -> { where(title: 'Portfolio title: 7') }

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
  end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_items, only: [:edit, :update, :destroy]
  access all: [:show, :index], user:{except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all

  layout 'portfolio'

  def index
    @portfolio_items = Portfolio.by_position    #.order("position ASC")
    #@portfolio_items = Portfolio.wrc
    #@portfolio_items = Portfolio.specific_portfolio_items
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end

    render nothing: true #dit a rails qu'on a pas besoin d appeler une vue. On a just update la databaase et on a fini
  end

  def new
    @portfolio_items = Portfolio.new
  end

  def create
    @portfolio_items = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_items.save
        format.html { redirect_to portfolios_path, notice: 'Portfolio item is now live.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    #@portfolio_items = Portfolio.find(params[:id])
  end

  def update
    #@portfolio_items = Portfolio.find(params[:id])

    respond_to do |format|
      if @portfolio_items.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'The Portfolio was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
    #This one has no s ! so it's not at the before action
    @portfolio_item = Portfolio.find(params[:id])
  end

  def destroy
    #@portfolio_items = Portfolio.find(params[:id])

    @portfolio_items.destroy

    #Redirect part
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:title, :subtitle, :body)
  end

  def set_portfolio_items
    @portfolio_items = Portfolio.find(params[:id])
  end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_blog_ruler.html.erb
<hr>

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_items) do |f| %>

  <% if @portfolio_items.errors.any? %>

    <%= @portfolio_items.errors.full_messages.each do | err | %>
      <%= alert_generator err %>
    <% end %>
  <% end %>

<div clas="row">

  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class:'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :subtitle %>
      <%= f.text_area :subtitle, class:'form-control' %>
    </div>
  </div>

  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, class:'form-control', rows: 13 %>
    </div>
  </div>

</div>


<div class="col-md-12">
  <div class="form-group">
    <%= f.submit 'Save Portfolio Item', class: 'btn btn-primary btn-block' %>
  </div>
</div>


<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4">
  <div class="card mb-4 shadow-sm" data-id="<%= portfolio_item.id %>">

    <%= image_tag portfolio_item.thumb_image , :class => "icard-img-top" unless portfolio_item.thumb_image.nil? %>
    <div class="card-body">
      <p class="card-text"><%=portfolio_item.body%></p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "View", portfolio_show_path(portfolio_item.id) %></button> <%# ici on a portfolio_show qui est definie par nous dans le routes.rb %>
          <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Edit", edit_portfolio_path(portfolio_item.id) if logged_in?(:site_admin)  %></button>
          <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Destroy", portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin)  %></button><%#on est pas obligé de mettre .id%>

        </div>
        <small class="text-muted">Updated <%= distance_of_time_in_words(portfolio_item.updated_at, Time.now) %> ago</small>
      </div>
    </div>
  </div>
</div>

app/views/portfolios/edit.html.erb
<div class="container portfolio-form">
  <h1>Edit this portfolio item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">

    <%= link_to "Create new  with link_to", new_portfolio_path if logged_in?(:site_admin) %>
    <%# the old was was doing <% @portfolio_items.each do |itemVar| pourcent> %>


    <div class="row <%= "sortable" if logged_in?(:site_admin) %>">

      <%# c'est important de noter qu ici c'est pas comme blog. On a un partial car portfolio_item est un nom qu'on a donné c'est pas just portfolio. %>
      <%= render partial: 'portfolio_item', collection: @portfolio_items, spacer_template: 'blog_ruler' %>
      <%# le spacer_template va mettre un separateur entre chaque portfolio. Il ne le met pas pour le premier et dernier. IL FAUT mettre partial pour qu il marche aussi %>

    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-form">
  <h1>Create a new portfolio item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-7">
      <%# au cas ou je n'ai pas de main image je mets le unless %>
      <%= image_tag @portfolio_item.main_image unless @portfolio_item.main_image.nil? %>
    </div>

    <div class="col-md-5">
      <h3><%= @portfolio_item.title %></h3>

      <em><%= @portfolio_item.subtitle %></em>

      <p><%= @portfolio_item.body %></p>

      <p><%= @portfolio_item.created_at %></p>

      <%= link_to "View all portfolio items", portfolios_path %>

      <br/><br/><br/><br/>
      <% if logged_in?(:site_admin) %>
        <div class="">
          <%= link_to "Edit item", edit_portfolio_path(@portfolio_item), class: 'btn btn-warning' %>
        </div>
      <%end %>

    </div>

  </div>
</div>