config/routes.rb
Rails.application.routes.draw do

  resources :topics, only: [:index, :show]

  resources :comments
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do     #Toutes les ressources sauf le show qu'on fait nous meme
    put :sort, on: :collection
  end


  get 'mon-portfolio/:id', to: 'portfolios#show', as: 'portfolio_show' #cet alias portfolio_show est appele depuis la vue dans index de portfolio

  # get 'pages/home'  #this was there but we commented it
  # get 'pages/about'
  get 'about-thomas', to: 'pages#about'

  # get 'pages/contact'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  #Pour la partie commentaires des blogs
  mount ActionCable.server => '/cable'

  #ca va dire que la default page c'est ca
  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
  <%= js add_gritter(flash[:alert], title: "Thomas Lefèvre Portfolio", sticky: false) %>
<% elsif flash[:error] %>
    <%= js add_gritter(flash[:error], title: "Thomas Lefèvre Portfolio", sticky: false) %>
<% else flash[:notice] %>
  <%= js add_gritter(flash[:notice], title: "Thomas Lefèvre Portfolio", sticky: false) %>
<% end %>

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner">
    <p><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">Thomas Lefèvre</h3>
    <nav class="nav nav-masthead justify-content-center">
      <%= link_to "Home", root_path, class: 'nav-link' %>
      <%= link_to "About", about_thomas_path, class: 'nav-link' %>
      <%= link_to "Contact", contact_path, class: 'nav-link' %>
      <%= link_to "Blog", blogs_path, class: 'nav-link' %>
      <%= link_to "Portfolio", portfolios_path, class: 'nav-link' %>

      <%= login_helper 'nav-link' %> <%# Celui la est un helper. Pas un partial car on a de la logique dedans donc on a fait un helper %>
    </nav>
  </div>
</header>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p><%= copyright_generator %>></p>
  </div>
</footer>

app/views/shared/_portfolio_nav.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Bla bla lba for my portfolio. I love rails youhouuu :))))</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Explore</h4>
          <ul class="list-unstyled">
            <li><%= link_to "Home", root_path, class: 'text-white' %></li>
            <li><%= link_to "About", about_thomas_path, class: 'text-white' %></li>
            <li><%= link_to "Contact", contact_path, class: 'text-white' %></li>
            <li><%= link_to "Blog", blogs_path, class: 'text-white' %></li>
            <li><%= link_to "Portfolio", portfolios_path, class: 'text-white' %></li>
            <li><%= login_helper 'text-white' %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
        <strong>Thomas Lefèvre</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>